### ISSUE TITLE
`Cound not found source at: path/to/my_keyfile` when step detach is set to true

### ISSUE THREAD

**Issue by MickPlaYer** [sinlead/drone-cache#4]
``` yaml
steps:
  - image: sinlead/drone-cache:1.0.0
    volumes:
      - name: cache
        path: /cache
    name: save-cache
    detach: true # This cause the error
    settings:
      key: path/to/my_keyfile
      mount: /my_cache
      prefix: my-cache-v1
      action: save
```
